# application name is eureka-server
spring:
  application:
    name: eureka-server
#  security:
#    basic:
#      enabled: true
#    user:
#      name: root
#      password: root

---
spring:
   profiles: peer1

# eureka server post config
server:
  port: 8761

# eureka server config
eureka:
  instance:
    hostname: peer1
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8762/eureka/

---

spring:
   profiles: peer2

server:
  port: 8762
# eureka server config
eureka:
  instance:
    hostname: peer2
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/
